### ISSUE TITLE
Do cancel schedule

### ISSUE THREAD

**Issue by Tian99** [LabNeuroCogDevel/LNCDschedule#20]

**Comment by Tian99** [comment]
Read triggers first.

**Comment by patelnilay** [comment]
I'd like to contribute to this issue. What would you like done?
(My first attemp at an opensource issue).

**Comment by Tian99** [comment]
Hi, since Will hasn't replied, This one is basically implementing the delete button in the visits table on the middle right of the user interface(Right click the row will show). Since delete(sql command) cannot be implemented directly on view(table that only shows the content). Triggers must be amended so that the effect on view could be passed on to its host. Or there might be another way around.

**Comment by Tian99** [comment]
should look roughly like the following code and should be added directly on trigger
(Still having some issues with the code)

####################################
create trigger tr_visit_summary_InsteadOfDelete
on visit_summary
instead of delete
as
begin
declare vid = int
select vid = vist.vid
from visit
join deleted.vid
on deleted.vid = visit.vid

end

**Comment by Tian99** [comment]
done
